apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dispatcharr
  labels:
    app.kubernetes.io/name: dispatcharr
spec:
  rules:
  - host: dispatcharr.dubyatp.xyz
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: dispatcharr-svc
            port: 
              number: 9191
