apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netmaker-ui-ingress
spec:
  rules:
  - host: dashboard.netmaker-test.infra.dubyatp.xyz
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: netmaker-ui
            port: 
              number: 80