apiVersion: v1
kind: ConfigMap
metadata:
  name: vaultwarden-config
data:
  DATA_FOLDER: config
  DOMAIN: https://vaultwarden.dubyatp.xyz
  SIGNUPS_ALLOWED: "false"
  SMTP_FROM: vaultwarden@em924671.dubyatp.xyz
  SMTP_FROM_NAME: Vaultwarden
  SMTP_HOST: mail.smtp2go.com
  SMTP_PORT: "2525"
  SMTP_SECURITY: "off"
  SMTP_TIMEOUT: "15"
  SMTP_USERNAME: vaultwarden_dubyatp
