apiVersion: v1
kind: ConfigMap
metadata:
  name: peertube-config
data:
  PEERTUBE_INSTANCE_NAME: "dubyatp peertube"
  PEERTUBE_INSTANCE_DESCRIPTION: "duby's peertube instance"
  POSTGRES_USER: peertube
  POSTGRES_DB: peertube
  PEERTUBE_DB_USERNAME: peertube
  PEERTUBE_DB_HOSTNAME: weyma-pgsql-rw.cloudnativepg.svc.cluster.local
  PEERTUBE_DB_PORT: "5432"
  PEERTUBE_WEBSERVER_HOSTNAME: "tube.dubyatp.xyz"
  PEERTUBE_TRUST_PROXY: '["127.0.0.1", "loopback", "172.18.0.0/16"]'
  PEERTUBE_SMTP_USERNAME: "peertube_dubyatp"
  PEERTUBE_SMTP_HOSTNAME: "mail.smtp2go.com"
  PEERTUBE_SMTP_PORT: "465"
  PEERTUBE_SMTP_TLS: "true"
  PEERTUBE_SMTP_FROM: "peertube@em924671.dubyatp.xyz"
  PEERTUBE_ADMIN_EMAIL: "me@williamtpeebles.com"
  #PEERTUBE_OBJECT_STORAGE_ENABLED: "true"
  #PEERTUBE_OBJECT_STORAGE_ENDPOINT: "https://weyma-s3.infra.dubyatp.xyz"
  #PEERTUBE_OBJECT_STORAGE_REGION: ""
  #PEERTUBE_OBJECT_STORAGE_STREAMING_PLAYLISTS_BUCKET_NAME: "peertube-953221d2-7649-48b2-b79f-5a9e59daedbb"
  #PEERTUBE_OBJECT_STORAGE_STREAMING_PLAYLISTS_PREFIX: "streaming/"
  #PEERTUBE_OBJECT_STORAGE_WEB_VIDEOS_BUCKET_NAME: "peertube-953221d2-7649-48b2-b79f-5a9e59daedbb"
  #PEERTUBE_OBJECT_STORAGE_WEB_VIDEOS_PREFIX: "videos/"
  #PEERTUBE_OBJECT_STORAGE_USER_EXPORTS_BUCKET_NAME: "peertube-953221d2-7649-48b2-b79f-5a9e59daedbb"
  #PEERTUBE_OBJECT_STORAGE_USER_EXPORTS_PREFIX: "exports/"
  #PEERTUBE_OBJECT_STORAGE_ORIGINAL_VIDEO_FILES_BUCKET_NAME: "peertube-953221d2-7649-48b2-b79f-5a9e59daedbb"
  #PEERTUBE_OBJECT_STORAGE_ORIGINAL_VIDEO_FILES_PREFIX: "original-videos/"
  #PEERTUBE_OBJECT_STORAGE_CAPTIONS_BUCKET_NAME: "peertube-953221d2-7649-48b2-b79f-5a9e59daedbb"
  #PEERTUBE_OBJECT_STORAGE_CAPTIONS_PREFIX: "captions/"
  #PEERTUBE_OBJECT_STORAGE_UPLOAD_ACL_PUBLIC: "public-read"
  #PEERTUBE_OBJECT_STORAGE_UPLOAD_ACL_PRIVATE: "private"